openapi: 3.0.0
info:
  title: Bumper API
  version: 1.1.0
  description: API para aplicación de registros y gestión de incidentes urbanos.
servers:
  - url: http://localhost:8080
    description: Servidor local para desarrollo
paths:
  /v1/users/create:
    post:
      summary: Crear usuario
      description: Registra un nuevo usuario en el sistema.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioRespuesta'

  /v1/users/login:
    post:
      summary: Iniciar sesión
      description: Permite a un usuario autenticarse utilizando sus credenciales.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                  description: Correo del usuario
                password:
                  type: string
                  description: Contraseña del usuario
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioRespuesta'
        '401':
          description: Credenciales inválidas

  /v1/incidentes:
    post:
      summary: Crear incidente
      description: Crea un incidente asociado al usuario.
      tags:
        - Incidentes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Incidente'
      responses:
        '201':
          description: Incidente creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidenteRespuesta'

    get:
      summary: Recuperar todos los incidentes
      description: Lista todos los incidentes registrados en la base de datos.
      tags:
        - Incidentes
      responses:
        '200':
          description: Incidentes recuperados exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IncidenteRespuesta'

  /v1/incidentes/usuario/{usuarioId}:
    get:
      summary: Recuperar incidentes por usuario
      description: Lista los incidentes asociados a un usuario específico.
      tags:
        - Incidentes
      parameters:
        - in: path
          name: usuarioId
          required: true
          schema:
            type: integer
          description: ID del usuario
      responses:
        '200':
          description: Incidentes recuperados exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IncidenteRespuesta'

  /v1/users/me:
    get:
      summary: Consultar datos del usuario
      description: Recupera información del usuario según el correo.
      tags:
        - Users
      parameters:
        - in: header
          name: correo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos del usuario recuperados exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioRespuesta'

  /v1/users/logout:
    post:
      summary: Cerrar sesión
      description: Cierra la sesión del usuario autenticado.
      tags:
        - Users
      parameters:
        - in: header
          name: correo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sesión cerrada correctamente
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Usuario:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del usuario
        apellido:
          type: string
          description: Apellido del usuario
        correo:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
        token:
          type: string
          description: Estado del usuario (activo o inactivo)
        numeroIncidentes:
          type: integer
          description: Número de incidentes asociados al usuario
      required:
        - nombre
        - apellido
        - correo
        - password

    UsuarioRespuesta:
      type: object
      properties:
        id:
          type: integer
          description: ID único del usuario
        nombre:
          type: string
          description: Nombre del usuario
        apellido:
          type: string
          description: Apellido del usuario
        correo:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
        token:
          type: string
          description: Estado del usuario (activo o inactivo)
        numeroIncidentes:
          type: integer
          description: Número de incidentes asociados al usuario
        incidentes:
          type: array
          description: Lista de incidentes asociados
          items:
            $ref: '#/components/schemas/Incidente'

    Incidente:
      type: object
      properties:
        usuarioId:
          type: integer
          description: ID del usuario asociado al incidente
        tipoIncidente:
          type: string
          description: Tipo de incidente
        ubicacion:
          type: string
          description: Ubicación del incidente
        tipoVialidad:
          type: string
          description: Tipo de vialidad donde ocurrió el incidente

    IncidenteRespuesta:
      type: object
      properties:
        id:
          type: integer
          description: ID único del incidente
        usuario:
          $ref: '#/components/schemas/UsuarioRespuesta'
        tipoIncidente:
          type: string
          description: Tipo de incidente
        ubicacion:
          type: string
          description: Ubicación del incidente
        horaIncidente:
          type: string
          format: date-time
          description: Hora en la que ocurrió el incidente
        tipoVialidad:
          type: string
          description: Tipo de vialidad donde ocurrió el incidente
